GET http://localhost:8000/ok
###
GET http://localhost:8000/timeout
###
GET http://localhost:8000/purchase
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJldmFoQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc0MjMwNjUwNn0.zCakhicYUO1m2nd8e_FWaT-jeZjH5PnzbM-_lTG7xZk
###
GET http://localhost:8000/reviews
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJldmFoQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc0MTk2NzIxOH0.1lmyVCQBPAOGHXvJLtNQIP-aBAPb-14PvwJt7JnPXlk  
###
POST http://localhost:8000/reviews
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJncmFjZUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImV4cCI6MTc0MTk1NDQ4NX0.XVIuSRdUcINWjAH8Vl9SziT2wy_TooFQ1-7wJkPtALk
Content-Type: application/json

{
    "user_id": 21,
    "rating": 5,
    "comment": "Kenya"
}

###
POST http://localhost:8000/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJncmFjZUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImV4cCI6MTc0MTk1NDQ4NX0.XVIuSRdUcINWjAH8Vl9SziT2wy_TooFQ1-7wJkPtALk
Content-Type: application/json

{
    "purchase_id":1,
    "user_id": 21,
    "amount": 5000,
    "status": "pending",
    "phone_number": "0796705177"
}

###
POST http://localhost:8000/location
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqdW5lQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTczODE4MTI5OX0.KN1qeyrbN5MI6j45BIrsWPTJOSw0RgvmYjJz3Mozg9M
Content-Type: application/json

{
    "city": "Nairobi",
    "state": "Nairobi",
    "country": "Kenya",
    "address": "Nairobi CBD",
    "zip_code": "00100"
}
###
POST http://localhost:8000/purchase
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJraWJpcmFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJleHAiOjE3NDIzMDU5NDR9.RQU3SJqEk1cemLpEZHEEymmOKUrs9JP0wHpTCtfrea8
Content-Type: application/json

{
     "user_id": 14,
    "property_type": "house",
    "property_id": 1,
    "total_amount": 100000,
    "location_id": 1,
    "purchase_status": "pending"
}
###
POST http://localhost:8000/register
Content-Type: application/json

{
     "full_name":"grace",
     "email":"grace@gmail.com",
    "password":"password",
    "contact_phone":"09876540987",
    "address":"Nyeri",
    "role":"user"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "evah@gmail.com",
    "password":"password"
}
###